
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class t_ad
{

    public int ad_id { get; set; }

    public string ad_name { get; set; }

    public Nullable<byte> ad_type { get; set; }

    public string ad_img { get; set; }

    public Nullable<byte> click_type { get; set; }

    public string click_value { get; set; }

    public Nullable<byte> sort { get; set; }

}

}
