
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class t_comment
{

    public int comment_id { get; set; }

    public Nullable<int> user_id { get; set; }

    public Nullable<int> order_id { get; set; }

    public Nullable<int> goods_id { get; set; }

    public string comment { get; set; }

    public string comment_imgs { get; set; }

    public Nullable<bool> is_del { get; set; }

    public Nullable<System.DateTime> create_time { get; set; }



    public virtual t_user t_user { get; set; }

}

}
