
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class t_order_info
{

    public t_order_info()
    {

        this.t_order_goods = new HashSet<t_order_goods>();

    }


    public int order_id { get; set; }

    public Nullable<byte> order_type { get; set; }

    public string order_sn { get; set; }

    public Nullable<int> user_id { get; set; }

    public Nullable<byte> order_status { get; set; }

    public Nullable<byte> shipping_status { get; set; }

    public Nullable<byte> pay_status { get; set; }

    public string consignee { get; set; }

    public string mobile { get; set; }

    public string area { get; set; }

    public string building { get; set; }

    public string room_num { get; set; }

    public string address { get; set; }

    public string postscript { get; set; }

    public Nullable<decimal> goods_amount { get; set; }

    public Nullable<int> uc_id { get; set; }

    public Nullable<decimal> uc_amount { get; set; }

    public Nullable<decimal> order_amount { get; set; }

    public Nullable<decimal> money_paid { get; set; }

    public Nullable<System.DateTime> add_time { get; set; }

    public Nullable<System.DateTime> confirm_time { get; set; }

    public Nullable<System.DateTime> pay_time { get; set; }

    public Nullable<System.DateTime> shipping_time { get; set; }

    public Nullable<System.DateTime> cancel_time { get; set; }

    public string expect_shipping_time { get; set; }



    public virtual ICollection<t_order_goods> t_order_goods { get; set; }

}

}
