//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_order_goods
    {
        public int rec_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> goods_id { get; set; }
        public string goods_name { get; set; }
        public Nullable<int> goods_number { get; set; }
        public Nullable<decimal> market_price { get; set; }
        public Nullable<decimal> goods_price { get; set; }
    
        public virtual t_order_info t_order_info { get; set; }
    }
}
