//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_psw_code
    {
        public int id { get; set; }
        public string user_phone { get; set; }
        public string v_code { get; set; }
        public Nullable<bool> is_use { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    }
}
