
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class t_shipping_blacklist
{

    public int sb_id { get; set; }

    public string area { get; set; }

    public string building { get; set; }

    public string floor { get; set; }

    public Nullable<System.DateTime> add_time { get; set; }

}

}
