//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_address
    {
        public int address_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string receipt_person { get; set; }
        public string receipt_phone { get; set; }
        public string university { get; set; }
        public string area { get; set; }
        public string building { get; set; }
        public string room_num { get; set; }
        public string address { get; set; }
        public Nullable<bool> is_default { get; set; }
    }
}
