//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_coupon
    {
        public int uc_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> coupon_id { get; set; }
        public Nullable<decimal> coupon_amount { get; set; }
        public Nullable<System.DateTime> begin_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<bool> is_use { get; set; }
        public Nullable<System.DateTime> use_time { get; set; }
        public Nullable<decimal> condition_amount { get; set; }
    }
}
